### ISSUE TITLE
Hook up footsteps

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#101]
We now have a few sets of footstep material sounds; we should try to hook these up to existing maps where appropriate (snow patches on Fractures, glass floors on wake, metal stuff, etc).

See edge.mat for an example of this, since it uses the grass one already.

**Comment by Panjoo** [comment]
Noted!

**Comment by jdolan** [comment]
@Paril Assigning this to you as you saw a bug with material loading and footsteps.

**Comment by jdolan** [comment]
Anyone working on map updates should take the opportunity to add footsteps to the materials files. We have multiple sets of footstep sounds for wood, grass, snow, ice, metal, etc.

#120 #119 #118 #117 #116 #115 #114 #113 #112

**Comment by jdolan** [comment]
I'll take a few minutes and update all of the q2dm maps next time I'm in there.
