### ISSUE TITLE
Lightmaps wrong on mingw32

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#103]
https://gm1.ggpht.com/NsFLUjMST8DmwVMe4BcUCnmD30lkKSUZFHQ9Q3s6-484zoyPNV3QdYRvcEJYxkSsSUEwi0Nil0ICOk5aXUS-LLzGT2wpBcfbvv8jz2F865pYvnA5izNJE9HmuwTmzoNuF5F2XMPUDEyJcYfuG3-FG186Mvu62XEPe1f9ncsSdihVaKWia29Rb003cojR7UBix17SNMde7U3155ph7a-EXb_fm81Ivn0k8vfv44sJaMZRuGC52cmlc5OZ1NH1sD9lZDdvkQoR2f_fQyc1wHFqQX1A3E-_sCMZZjubHKVlZgpIpleuqecIaGgBUp724qFQMa8ooU7eqgYcziSAUsv7WZsKMis0G4V_EGT3SnUZm_Ki9jE1UdEDnS3YiJ1w0PBlVzagy1ZbsyYDeYTYQXaWCnRhggq7tPOnTApfQVrE0Jk2HGOQ0M0pjcaxQDZ3PYwRp_yJ5ZJyOF-WdaMCD-hYWuFNRaHxQC0qT5Vef3i_v5FJ3AzKiaKIKQnD-cORWahl8FodLukPUL5KSBEwoXK4xcULXDrwVHOfGjPzmchHqoT1IcXHALBA0UQ4YN6JVa-4XkIy4A5nnnC1-Yt1ve39ndP4saJf_q-5MoYzPOiPCixcyObpd6A7eEvgopHjuBg22OVL7ML0SHZMajz8ni7jEP3oGXogADBTNFLKtN0B9pTwWPzRRxU=w2048-h1152-l75-ft

This was reported by @Panjoo. Pan, can you try running r_draw_bsp_lightmaps 1 and see if the lighting errors show up there? If not, it's likely related to diffuse lighting shader and not lightmaps.

**Comment by Panjoo** [comment]
Okay, this is with r_draw_bsp_lights 1 and the errors show up there as you can see;

![quetoo067](https://cloud.githubusercontent.com/assets/10857572/26027214/4a1cafb4-380a-11e7-89d0-d987b57a1eec.jpg)

It's nothing I haven't seen before when it comes to lighting bugs, but it's strange that this wasn't there and suddenly pops up. 
I already tried some things like making new lights and moving them around but that doesn't fix it. Doublechecked the light properties and compared them with lights that don't have this problem but I can't find anything. There are some more things I could try like moving the entire map to another location on the worldgrid but that could sometimes cause other oddities.

**Comment by kaadmy** [comment]
Is there a light inside geometry there?

**Comment by Paril** [comment]
Had you updated your grunt.bsp at all or is it the same one in master? I can't reproduce these issues there. It looks more like it's using the wrong piece of the lightmap for that surface rather than the lightmap itself being corrupt. Are you loading any other maps before this one?

Can you load into map grunt immediately after launching, do r_dump_images, then attach the lightmap files that are generated inside My Games\Quetoo\default\imgdump\ ?

**Comment by Paril** [comment]
This is related to mingw build. :(

**Comment by Paril** [comment]
![lightmap 0](https://cloud.githubusercontent.com/assets/1224734/26028100/8ecc4a34-37e7-11e7-900c-826f6ec12f35.png)

**Comment by Panjoo** [comment]
@Paril, ^Yep, the generated _lightmap 0.png_ looks the same as the one above, with the larger black area.
Lol, I never knew a lightmap looked like this, kinda cool actually. I did check out some other maps and Grunt seems the only one that shows this problem.


@Kaadmy, nope there are no lights inside geometry, it was all fine before. To see if it was maybe a map error I did some tests (locally), put new lights in and even tried rebuilding the geometry there but that didn't help. Only if I took out those particular lights the floor looked normal, that is with just the ambient light.

**Comment by Paril** [comment]
@panjoo the issue is limited to the mingw build, which is why we never noticed it. It may be a regression from jdolan updating the build tools. I'll figure this one out today. Also: that's just how Quetoo turns the light map into a texture, the light map is actually entirely 1 dimensional in the BSP, which is even cooler (its a long string of data rather than a rectangle like ours).

**Comment by kaadmy** [comment]
@Paril well technically all images (PNG, TGA, etc) are all 1d ;)

**Comment by Paril** [comment]
Fixed in latest commit.

**Comment by jdolan** [comment]
Crazy.

So what happened here, @Panjoo, is that before @Paril merged his OpenAL changes into master, I did some routine maintenance on the build machine, to ensure that it had the OpenAL and libVorbis libraries installed etc -- so that the build would succeed.

Part of that routine maintenance was updating the tool chain (the C compiler and other standard things). For whatever reason, the new version of the compiler that was installed through the system update utility _changed_ how floating point variables were handled. @Paril narrowed in on this after hours of debugging.

The fix was to add some compiler flags for floating point precision to just the MinGW build -- it's the only build that was affected.

Crazy. But anyway, I guess it's fixed!

**Comment by Panjoo** [comment]
Wow dudes, good work finding the problem. Why does everything has to be so complicated, ugh!

I found it was also screwing with Warehouse's lightmap. The bastard!
![badlightmap](https://cloud.githubusercontent.com/assets/10857572/26036481/c3e7507c-38de-11e7-8a86-6891b40ec4b9.jpg)
