### ISSUE TITLE
Quake 2 logo on Fragpipe and Edge

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo-data#105]
On Fragpipe, the central atrium's upper level has a (partial) Quake 2 logo on it. This should probably be replaced with a Quetoo logo or something.

**Edit:** the same logo is on the large crates on Edge too.

**Comment by Panjoo** [comment]
That's not the trademarked quake2 logo, it's a subtle hint at the logo. Sigh:/

> ...replaced with a Quetoo logo or something

Provide me textures that are of equal quality and fit perfectly in these maps and I'll consider changing them.

**Comment by kaadmy** [comment]
I _did_ say they were partial logos ;)
I'll try remaking them anyway just for practice.

**Comment by kaadmy** [comment]
So I just spent about half hour trying to get GIMP normalmaps to work correctly :|
