### ISSUE TITLE
Gehenna minor bugs

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#107]
- [x] Thunder sound sample is stereo, and a warning prints when it is mixed in game
- [x] Outer teleporter still has `SURF_WARP`, whereas the inner teleporter does not. The inner teleporter looks much better.

**Comment by ptrvrhvn** [comment]
The sound was already fixed apparently. I fixed the teleporter.
f93ab48c33c0cb2d3a887e6f4bfb117be08f973a

**Comment by jdolan** [comment]
Thanks for fixing the teleporter, @ptrvrhvn 

I noticed a bunch of other bugs just now on the map. I checked to make sure I didn't have any stale materials files or BSPs floating around.

![quetoo001](https://user-images.githubusercontent.com/643118/35566552-d11dcaae-058f-11e8-99c8-9c4d981292f6.png)

Standing near the two teleporters, a loud, high pitched hissing sound is heard. This can't be on purpose. Something must be off.

![quetoo000](https://user-images.githubusercontent.com/643118/35566561-d8ac35bc-058f-11e8-9ecb-dc3b4056c615.png)

The jump pad material is broken. It's supposed to look like the pads on Aerowalk, but there's no visible material animation here.

![quetoo002](https://user-images.githubusercontent.com/643118/35566606-f4e090fc-058f-11e8-9e91-c34e399cbb0b.png)

There's a visibility error around this jump pad.

Also, none of the lava areas have material animations. That can't be right (?)

**Comment by ptrvrhvn** [comment]
Oh wow, not sure how I missed those things, it was getting late I guess.
I just opened the map, made the change and ran Quemap with -zip. I'll look into it.

**Comment by jdolan** [comment]
The `func_door_rotating` (the big oil drill outside) is blowing out `MAX_ENT_LEAFS`. If you `debug collision` while running around the map, as soon as that puppy moves, you'll see this message. We may need to simplify the area around the oil driller, or shrink the pump in size, or consider increasing `MAX_ENT_LEAFS`.

**Comment by jdolan** [comment]
The jump pads have the yellow effect stage, but it is not animated with `stretch`. See Aerowalk's materials file for the same effect.

**Comment by kaadmy** [comment]
I didn't notice any of these problems anymore, I think the only thing I didn't check was the oil drill.

**Comment by jdolan** [comment]
It's worth re-checking the oil drill. I pushed a fix for Sv_LinkEntity last night that could affect it.

**Comment by jdolan** [comment]
I fixed this (same error on Pits and probably other maps) by increasing MAX_ENT_LEAFS and MAX_ENT_CLUSTERS. All set!
