### ISSUE TITLE
Convert all normalmaps to RGB and re-zip maps

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#129]
We've recently dropped parallax mapping, and so there's no reason to include heightmaps or alpha-channel normalmaps in our game assets. Batch-converting all normalmaps that we have would allow us to:

1. Spot the ones that are shit (alpha transparency makes this hard to detect)
2. Save some disk space on pk3 archives

This can be done by simply:

1. Unzipping all pk3's to ~/.quetoo/default
2. Running a batch conversion on `*_nm.*, *_norm.*, *_local.*, *_bump.*` from RGBA to RGB using ImageMagick
3. Re-zipping all pk3's (`quemap -zip maps/my.map`)

**Comment by jdolan** [comment]
Whoever takes this ticket should also edit all of the materials files to delete the parallax lines. They are harmless, but noise at this point.

**Comment by Panjoo** [comment]
Problem with the used textures is that, in order for parallax shadows to look better, I had to get rid of any drawn shadows. Like baked-in shadow borders that conflicted with the realtime shadowing. But now without the parallax shading, they look too flat.

I'm already going through the used textures one more time in photoshop to add back some more contrast and depth. My photoshop has the 'action-record' feature which allows me to do this easy and quick.
I'll also get rid of the 32bit alpha channels from the _normals. I'm making new pk3's anyway now that I'm going over the maps one last time.

**Comment by jdolan-chwy** [comment]
We should just be able to tune the normalmaps (or even easier: just ramp up the `roughness` in the material file, which multiplies the X and Y but not the Z of the normalmap color) to give the textures more definition with respect to lighting. We shouldn't have "fake light" in the textures at all, parallax or no parallax.

**Comment by jdolan-chwy** [comment]
Either way, tho, thank you for doing this! 😍

**Comment by Panjoo** [comment]
Yes, one of the first things I noticed was that increasing the `roughness` has a nice effect. 
I also started testing with fresh .materials for the maps, and I have to say that with everything reset to 1 (default) it looks not half bad. From what I can tell at this point, I got a good feeling about this.

**Comment by jdolan-chwy** [comment]
Nice! You know about `quemap -mat my/map.map` generating a "clean" material file for you right?

**Comment by Panjoo** [comment]
> ... get rid of the 32bit alpha channels from the _normals
... also edit all of the materials files to delete the parallax lines.

 -> This is done and will all be included in the Re-Zipped pk3's when they're ready.
