### ISSUE TITLE
The Warehouse

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo-data#2]
TRaK is working on a remake of q2dm8. Opening this ticket to log any issues / progress updates.

    owner trak deleted
    status changed from new to assigned

r1618 adds map-q2wdm8.pak to branches/wip. The map is a near pixel-perfect rebuild of the original level.

What's left:

    Lighting could use some tuning
    Details such as light fixtures and various eye candy
    Some weapons and items are missing (e.g. railgun)
    Materials definitions are not yet tuned (e.g. no parallax)

**Comment by jdolan** [comment]
Pan..
