### ISSUE TITLE
Chastity Belt Duel

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#28]
Jalisk0 gave us permission several years ago to port q2rdm2. You can find `chastity.map` available in `src/default/maps`. We should retexture this one in something tech / modern. Perhaps using one of Phil K's free texture sets?

**Comment by kaadmy** [comment]
The lighting is beautiful :)

**Comment by jdolan** [comment]
This is probably the most popular 3rd party duel map for Quake2. It's up there with Aerowalk and Rage. I'd love to have this one done.

**Comment by kaadmy** [comment]
I'll just try to port this one but I won't be very strict about gameplay and just keep layout intact.

**Comment by jdolan** [comment]
That sounds great. This might be a good candidate for Rygel textures?

**Comment by kaadmy** [comment]
I'll try to use the philipk02 texture set, might not fit well.

**Comment by Panjoo** [comment]
How's this one going? I bet acquiring or creating the right textures is the problem, mine always is with map ports.

**Comment by jdolan** [comment]
Could always trak5 this puppy. I'd submit that we do not yet have a good looking, good playing map that uses those textures. If we did, I'd probably cut Trial or Wake or both :|

**Comment by WickedShell** [comment]
Trial seems close actually. (At least I've enjoyed it with others so far).
Wake I admit is problematic, but nice as a system test :) (Gameplay wise
it's a disaster for rockets/nades)

**Comment by jdolan** [comment]
@Panjoo nailed this one 8)

**Comment by SpineyPete** [comment]
It's one of my fav ones for sure!
