### ISSUE TITLE
Aerowalk

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#29]
Aerowalk (the original) was released without any restrictive licensing clauses, and so we're in the clear to port this one over. I've decompiled aeroq2.bsp, you'll find aerowalk.map in `src/default/maps`. Lunaran's Q4Power texture set is an obvious fit for this:

http://www.lunaran.com/page.php?id=8

**Comment by Panjoo** [comment]
https://github.com/jdolan/quetoo-data/commit/c4614c897e043993ad3d5c0e9f2c0b7f95856308
