### ISSUE TITLE
The Frag Pipe

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo-data#3]
TRaK expressed interest in retexturing our q2dm3 remake. While we only really 'need' better normalmaps, TRaK's textures would of course be great to have.

CC'ing Thorn since he has a related issue (#152, Frag Pipe normalmaps). Can you guys coordinate on who is doing what and when?

    owner trak deleted
    status changed from new to assigned

r1618 adds an updated quake2world-data/branches/wip/target/default/map-q2wdm3.pak that includes all new original textures by TRaK.

What's left before this map could be included in the game:

    Lighting is a little overdone
    More brushes should be used to increase the polygon count and "round out" certain areas of the map.
    Additional details and eye candy to bring the map up to par visually with e.g. Edge
    Because of Q2W's larger player bbox, certain areas of the map feel too tight
    Materials tuning

**Comment by jdolan** [comment]
Pan did it.
