### ISSUE TITLE
Prioritized sound list

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#38]
- [x] `sounds/misc/hit.wav` This is the "you inflicted damage on your enemy" sound. We'd like to add 2 variations of this (3 total) for the amount of damage inflicted; perhaps one higher pitch and one lower pitch? This is a nice one to get started with.
- [x] `sounds/weapons/blaster/fire.wav` Too high pitched, a little weak sounding. Original sound: https://youtu.be/7bGSC68K6OA?t=4m37s
- [x] `sounds/weapons/rocketlauncher/fire.ogg` Crack instead of a boom with a whoosh. Original sound: https://youtu.be/pRpXnvvqrMI?t=23s
- [x] `sounds/weapons/shotgun/fire.wav`, `sounds/weapons/supershotgun/fire.wav` A little quiet?
- [x] `sounds/weapons/bfg/fire.wav` Missing high-pitch wind up. Original sound (with Quad): https://youtu.be/dVowRGJYQWw?t=28s
- [x] `players/common/jump_*.wav` A little loud? `jump_1` also has an odd "coins in your pocket" sound. Maybe we should just lose `jump_1`.

- [x] `sounds/world/door_*_1.wav` Alternate stone / concrete door movement noises, that will be selectable by the map author via key-value pair.

More to come!

**Comment by jdolan** [comment]
@anthonywebb1 Updated with some initial direction for sound effects.

**Comment by jdolan** [comment]
@Panjoo Just so you're in the loop on this.

**Comment by anthonywebb1** [comment]
[Prioritized sounds.zip](https://github.com/jdolan/quetoo-data/files/457578/Prioritized.sounds.zip)

**Comment by jdolan** [comment]
Thanks @anthonywebb1! I had missed your comment on this for some reason. Anyway, these sounds are now available in Git and rsync. If you run Update.bat, you should receive them in `quetoo-001.pk3`. Here's my feedback:

 * Shotgun and SSG sound are maybe a bit too loud now? Sorry! They almost sound like they're distorting to me. I think somewhere in between the original sounds and the new ones is where we want to be.
 * Rocketlauncher's whooshing sound is great. The boom is still a little light in the trousers, if you ask me. It sounds like a tom instead of a kick, if that helps?
 * Blaster is better, but lacks the quintessential "Pew!" sound, and has a bit of a thud that seems odd.
 * Hit sounds are on point -- nicely done! These won't show up in game until I tweak the code to use them.
 * BFG, fucking nailed it. That is the Q2 BFG, but better. Absolutely perfect.

Thank you again for working on these!

**Comment by anthonywebb1** [comment]
[Amended sounds .zip](https://github.com/jdolan/quetoo-data/files/463974/Amended.sounds.zip)

**Comment by anthonywebb1** [comment]
- I've reduced the volume of the shotguns slightly (they were peaking before)

- Added a boom to the rocket launcher

- Scrapped the blaster and gone back and modified the original sound to add a filter sweep 'pew' sound and beefed up the bass slightly. (I see what you mean about the odd thud on the first one!)

- I've made a new sound for jump_1 if you want to replace the original version. It was quite difficult getting it to sound similar enough to the other original ones, so no worries if it doesn't fit right. 

- I've decreased the volume of each jump by 4db. Let me know if that's too much, or not enough...

- I noticed that all the original sounds are wav files. I did bounce my sounds down to be ogg but the quality is really noticeably reduced, so you might want to keep them as wav?

Let me know if these are more towards what you're looking for, cheers!

**Comment by jdolan** [comment]
Nice! The jump sounds are great, now, and I like your new, lower-pitched one. Shotty and SSG are spot on. Blaster and RL are both much improved; I dig 'em.

If you run Update.bat in a few minutes, you'll get the updated sounds via rsync. You can then test them out for yourself in-game. Bring down the console (`~`) and type:

    map edge
    give all

Side note, the sounds you attached this last time were stereo .wav, which the game will not load. Because the game does its own spatialization and mixing, it requires mono samples. No big deal; I just ran them all through Audacity to mix them down. Just an FYI for next time.

Speaking of next time, if you're happy with the RL and Blaster, we could look at:

  * `quad/*.wav` I made these on my Microkorg like 8 years ago. They're pretty bad ;) The general form of the sounds are correct, but they're missing all complexity and layering.
 * `world/plat_mid.wav`, `world/door_middle.wav` These are supposed to be looped samples that the game can trigger over and over while a door or platform is moving. They must also be short, so that if the game triggers the sound as the door or platform nears its end, the sound doesn't carry on for too long.

I got the impression that you weren't able to actually test your previous sounds in the game. You should be able to do so. Here's what I would recommend:

 * Go to `share/default` and unzip `quetoo-001.pk3` in place. You should then have `share/default/sounds`, among others.
 * Move `quetoo-001.pk3` to your Desktop or someplace for safe keeping.
 * Drop any updated files right over the existing ones in `share/default/sounds` and fire up the game.

Hope that helps, and thank you again for working on these!

**Comment by anthonywebb1** [comment]
[Quad.zip](https://github.com/jdolan/quetoo-data/files/465511/Quad.zip)

**Comment by anthonywebb1** [comment]
Let me know if the levels are ok. I did manage to test the sounds this time, by following your instructions, so they should all be compatible this time.

**Comment by jdolan** [comment]
Nice! The format is fine this time, yep. The levels are maybe a touch quiet.

**Comment by jdolan** [comment]
Oh, and the sounds themselves are definitely better than my horrible attempts ;)

**Comment by anthonywebb1** [comment]
[Loops.zip](https://github.com/jdolan/quetoo-data/files/470360/Loops.zip)

**Comment by anthonywebb1** [comment]
These are the loops I was having trouble with. Are these the ones you needed to modify?

**Comment by jdolan** [comment]
@anthonywebb1 That's them! Wanna try committing / pushing to Git?

**Comment by anthonywebb1** [comment]
Yes, I'll give it a go. Just waiting for the client to finish cloning the data and then I'll have a go at committing them

**Comment by jdolan** [comment]
@anthonywebb1 What would you think of introducing alternate, "stone" sounds for `door*.wav`? The door sounds that we have now are great for sci-fi themes. They are really out of place on gothic / ancient themed maps. They could be committed with a suffix (`door_start_1.wav`, etc..), and a simple key-pair in the entity definition in the `.map` file would allow the level designer to select them (`sounds: 1`).

Also, would you consider lowering the pitch of the blaster's fire sound? I think that would make it more reminiscent of Quake2's blaster.

**Comment by anthonywebb1** [comment]
Hi Jay,


Loving the new menus, and opening up the quetoo-001 into individual folders will definitely make things easier.


Yeah, I'll play around with the pitch of the blaster and see what I can do.


Definitely a good idea for a second set of stone door sounds for the ancient style maps, I'll get recording some sounds for the new effects.


Also, do you still need to enable the loop sounds for the door and the platform? I need to test the volume levels and find out if the loops sound clean.


Thanks


Anthony


________________________________

**Comment by jdolan** [comment]
Nice! Glad you like the menus. They're not done yet, but I'm happy to hear that they're an improvement :)

I've gone ahead and re-enabled `plat_mid`. If you update, you should hear it as well. It sounds like it's looping cleanly to me, but it is very quiet.

FYI, a great place to test the stone sounds for doors would be `darkzone`. There is a secret door in the middle of the floor of the main atrium, here:

![quetoo000](https://cloud.githubusercontent.com/assets/643118/18554539/8e96130a-7b32-11e6-9fc1-25f8544cf4a5.jpg)

Also, the massive ramps on `lavatomb` that move are both technically doors, and they too could possibly benefit from a more fitting sound:

![quetoo001](https://cloud.githubusercontent.com/assets/643118/18554669/f1b8449e-7b32-11e6-9e47-4be1087b89bf.jpg)

To test these, you could overwrite the default sounds, and once you're happy with them, add these to your Git working copy with numeric suffixes. If that's unclear, just lemme know and I'll walk you through what I mean.

And if all of this is too much, or you're struggling to determine which samples to overwrite, feel free to just create a few generic stone / concrete moving sounds, and I can tweak the code to accommodate them as best we can.

**Comment by jdolan** [comment]
@anthonywebb1 New RL sound is great! Nicely done!

**Comment by jdolan** [comment]
The new stone sounds are awesome! You can hear them on The Dark Zone's secret door.
