### ISSUE TITLE
Lilith: Caulk/Missing texture

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#41]
When in the small health pickup by the stairs with the rocket launcher, if you look straight up you see through what is clearly supposed to be a wall/acts as a wall.

**Comment by kaadmy** [comment]
https://usercontent.irccloud-cdn.com/file/v8P7wEYr/lilith.map

Fixed .map file, needs a compile still.

**Comment by kaadmy** [comment]
Fixed in commit b4cb3aeeeb17100ee4a8d094488f156c03313577
