### ISSUE TITLE
Hyperblaster is weirdly scaled / off-center

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#43]
I'm not sure exactly what it's deal is, but there's something strange with this model. It's very difficult to get it to look decent in the first person view at all. Even when you have it roughly where it should be, the perspective seems strange. And when you toggle the `hand` cvar (0, 1, 2) to switch it to left or right handedness, it moves much farther than the rest of the models. I'm *guessing* this is due to scaling, but I'm not sure. Is there any improvement that can be made here?

**Comment by Panjoo** [comment]
Yeah, I had noticed that while I was painting the skin. I'll see if I can adjust the model.
See attached image.
![hyperpower](https://cloud.githubusercontent.com/assets/10857572/18681511/b6788d28-7f68-11e6-971a-864c1b167de9.jpg)

**Comment by Panjoo** [comment]
I've tried a bunch of things including repositioning and adjusting the model itself. I can get it to look good with "hand 0" but I don't know what's going on with "hand 1 and 2". Doesn't make much sense again...

It would help if I knew how you make the handedness work - does it just rotate the model around its origin or maybe the center of mass? Does it also get moved on the y-axis?

**Comment by Panjoo** [comment]
Hopefully this commit [5f87b1d](https://github.com/jdolan/quetoo-data/commit/5f87b1d04cd465ff003fecffdea65202ff05ebcc) makes it less noticable. At least it looks like it moves slightly less far to the sides now that I adjusted the model's barrel and position on the grid. Best I can do for now.

**Comment by jdolan** [comment]
The handedness does not rotate the model at all, it only translates it +/- 6 units. Thanks for posting that screenshot, it perfectly illustrates what's wrong. Eventually we should just chop the model -- like a sawed off hyperblaster ;)

**Comment by jdolan** [comment]
I tweaked this a little more this evening. It's good enough for now. Thanks Pan.
