### ISSUE TITLE
Fragpipe lava can clip out of the kill tube

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#45]
Not even sure if that's what you call the tube, but from the armor side, if you trigger the lava trap the top plane of the lava will clip out of the tube (when viewed from a distance)

**Comment by jdolan** [comment]
Screenshot please?

**Comment by WickedShell** [comment]
Crashed on screenshot, will try to get it on my nix box

**Comment by WickedShell** [comment]
![quetoo007](https://cloud.githubusercontent.com/assets/567688/18806391/0451583a-81e0-11e6-8de7-a2d3afd3bcc3.jpg)
![quetoo008](https://cloud.githubusercontent.com/assets/567688/18806392/07fe9240-81e0-11e6-8024-3c7f38508935.jpg)

**Comment by jdolan** [comment]
Wow, thanks. I've never seen this!

**Comment by jdolan** [comment]
CC @Panjoo Lemme make sure this isn't code related before you attempt to fix it, but just wanted to let you know :)

**Comment by WickedShell** [comment]
I can only see it when relatively fast away from the tube which makes me
think it might be code related. (And it doesn't hurt me)

**Comment by kaadmy** [comment]
Do translucent objects have a depth offset? That would cause translucent objects(like lava) to clip through geometry from far away.

**Comment by Panjoo** [comment]
> CC @Panjoo Lemme make sure this isn't code related before you attempt to fix it, but just wanted to let you know :)

Lol Jay, thanks! But I'm pretty sure this was one of the reasons for me to keep the bridge as a func_door that sinks into the lava and not use the rising func_water entity after you had fixed it :P

**Comment by jdolan** [comment]
So this is just a materials bug. `r_materials 0` and the problem goes away. It probably has to do with the glPolygonOffset logic in `r_material.c`. Will investigate.

**Comment by jdolan** [comment]
Fixed.
