### ISSUE TITLE
Fragpipe: Ledge by YA and Quad should be removed

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#47]
It would be really nice to support using the hyperblaster to wallclimb to the quad from the YA area. At the moment the ledge is blocking that, and approaching from the walls doesn't work (I'm not sure if it's just a problem with a invisible clip or map space)

**Comment by Panjoo** [comment]
Oh no! :) I can understand how it would be nice to be able to just skate up there and take the quad like it's nothing. But that ledge is original and I deliberately put clip brushes on the walls to prevent players from doing just that! This is a good example of how these remakes of the classic Q2DM maps should stay faithful to their original gameplay and jumps. They should just look better but play the same, that's the goal here in my opinion. In other words I disagree with this proposition.
In the original Fragpipe map you either have to do a rocketjump to get up there or use the moving platform. And as much as I like the hyperclimbing, I already fear that it's going to change too much of the dynamics in the other map ports as well and not necessarily in a good way. (Note that I'm talking about the map ports of classic Q2, not other custom maps of course.)

**Comment by jdolan** [comment]
I think that the ledge is a good move, to make a trivial hyper-climb impossible. You could even extend the ledge, so that it protrudes along that entire wall. But the clip brushes on the adjacent walls are just weird. If people want to hyper-climb the adjacent walls and air-accel over, I personally think that's fine. It's okay to open up a few new possibilities on these old classics. I don't think that necessarily detracts from them.

**Comment by kaadmy** [comment]
Any progress/ideas for this one?

**Comment by Panjoo** [comment]
I'll remove the clipbrushes that are on the walls and probably extend the ledge. 

(I'm finally almost done with all those normals and other textures for Fractures and I'm also redoing that hyperblaster barrel, again... ugh I hate that stupid thing!)

**Comment by jdolan** [comment]
Awesome! And yea, maybe someday we'll just replace the hyperplasma, heh.

**Comment by jdolan** [comment]
@Panjoo fixed this one. I tested it, and was occasionally able to plasma-climb into the quad room via the ledge, but it's not a sure bet. On average, it took 2-4 tries. But I think this is the right compromise. @WickedShell please close this one out if you agree.

**Comment by WickedShell** [comment]
I can reliably make the climb and jump, you have to go a bit high otherwise you miss it but once you do it works fairly easily. Works for me! Thanks @Panjoo
