### ISSUE TITLE
Missing pickup icons

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#48]
Pickup icons for the various healths are all missing. If you look in the pics folder, you'll see ancient KMQuake2 HUD icons for these items. We should replace them.

Our existing health icon is also a bit out of place compared to the others. If that one can be made more consistent with the rest of our icons, that'd be great!

**Comment by Panjoo** [comment]
Is this something? I went ahead and merged these. As basic as it can get but that's the style of the HUD;)

![healthicons](https://cloud.githubusercontent.com/assets/10857572/18894673/8e92e2d4-8514-11e6-96c8-5be1aaf76486.jpg)

**Comment by WickedShell** [comment]
As long as the text below each isn't shown in game I'm good with it :)

**Comment by jdolan** [comment]
These are great, Pan. I wired them up this evening. Nice job!
