### ISSUE TITLE
Fragpipe: lava balls spawn above the lava pit

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#49]
The most minor of problems, most people will be dead to fast to notice :)

![quetoo009](https://cloud.githubusercontent.com/assets/567688/19005923/f860c29a-8711-11e6-8126-a1347388640a.png)

**Comment by jdolan** [comment]
I did that on purpose, to prevent them from triggering the water_exit sounds. But maybe they should trigger those sounds.. or maybe they should at least be placed closer to the surface of the lava.

**Comment by WickedShell** [comment]
Closer would work, it was just visually inconsistent as I was burning up in
the bottom :)

**Comment by Paril** [comment]
...or just have them exempt from those sounds? :p

**Comment by jdolan** [comment]
Yea, that would work. Good idea. Eat shit :P
