### ISSUE TITLE
Unneeded data

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo-data#52]
I've been going through the quetoo-data repository, and I've noticed a few data duplicates/old versions, such as the old RL model still being saved in the repo and having a duplicate railgun diffuse image.

Should this old/duplicate data be removed or is there still a use for it?

Files so far that I've found that seem unused:
- [ ] src/default/models/weapons (Some cleanup here, not sure exactly which files are outdated)
- [ ] src/default/pics (Some cleanup here, not sure exactly which files are outdated)
- [ ] src/default/sounds (BFG sound has since been split up, so this is outdated and redundant)
- [ ] src/default/models/weapons/rocketlauncher (Outdated)
- [ ] target/default/models/weapons/railgun/skin_glow.tga (Duplicate of the skin_glow.png)
- [x] target/default/models/health/small/tris.mtl
- [x] target/default/models/health/medium/tris.mtl
- [x] target/default/models/health/large/tris.mtl

Files that seem off/partially used:
- [x] target/default/models/health/large/skin_nm.tga (Should also be used for mega, medium and small health packs?)
- [ ] target/default/models/weapons/blaster/world.cfg (Missing? Should there be one or should zeroed world.cfgs be removed?)
- [ ] src/default/ui/icon.png _and_ src/default/icons/icon.png (Different, both are unused)
- [ ] src/default/pics/i_flag.xcf (New flag icon isn't in target/ yet)

**Comment by jdolan** [comment]
Yea, I'm sure there's some cruft. Please enumerate the assets you find here so that we can confirm they're no longer needed before we axe them.

**Comment by Panjoo** [comment]
> target/default/models/weapons/railgun/skin_glow.png

The PNG version of the glow is the correct one, the TGA can be deleted. 

I'll get on this Unneeded data stuff as soon as I get the chance to re-clone the data repository and sift through it. In fact most of the .psd's in 'scr' are not relevant anymore as I've heavily modifyed them.

**Comment by jdolan** [comment]
👍

**Comment by kaadmy** [comment]
*bump*

**Comment by kaadmy** [comment]
Some stuff here is already done, is @Panjoo doing this one?

**Comment by Panjoo** [comment]
There's going to be a big cleanup. Before I actually moves file around and delete stuff I'm trying to clean and organize all those large psd's (offline) and optimize them so that they're actually up-to-date and useful for keeping. I need to be going now but I'll be going through data tonight.

(Btw did you pm me on discord yesterday? Been checking it out and I was scrolling up through old messages when I noticed a red thingie an hour later. Lol, Hello!)

**Comment by kaadmy** [comment]
Hi on Discord :)

**Comment by Panjoo** [comment]
One or two files might have slipped through but this is mostly all been taken care of. 
Phew!!
