### ISSUE TITLE
Trial: Ceiling clip has holes

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#53]
You can escape onto the top of light fixtures in trial. There is an invisible floor you can walk around. See the attached demo (or no_clip into the area).

[trial.zip](https://github.com/jdolan/quetoo-data/files/535138/trial.zip)

**Comment by jdolan** [comment]
LOL -- nice maneuver.

I think this actually shows off just how badly Trial needs another vertical level. There's so much detail up there that you never really notice when running around in the map.
