### ISSUE TITLE
Fragpipe: Ladder brush on pipe

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#54]
The fragpipe on fragpipe allows you climb it as a ladder. (Screenshot is while on the ladder)

![quetoo029](https://cloud.githubusercontent.com/assets/567688/19838795/e5638cb0-9e93-11e6-955e-5979f4fbd439.png)

**Comment by jdolan** [comment]
Hah! I also noticed this small texture niggle.

![quetoo006](https://cloud.githubusercontent.com/assets/643118/19865496/e0ebda22-9f72-11e6-823d-64854167df22.png)

**Comment by Panjoo** [comment]
@WickedShell - that is a well known 'bug' that people still use as a trickjump shortcut (see demo)
[dm3jumpdemo.zip](https://github.com/jdolan/quetoo-data/files/562680/dm3jumpdemo.zip)

I'd figured most of you would be just as familiar as I am with the stock quake2 maps but I guess not. Ask claire/Joe about this pipe climb thing:) I still play these maps regularly online and it will be a letdown for true fans if I take out all the little quirks from these map ports.

(As for the stair steps, I'll see if I can add in one extra step to those sets of stairs to go from 3 to 4 to make them less heigh, just to make sure.)

@jdolan - ^ Seriously, I left that little misalignment in the map for you to find, to test your observation skills and to let you think you're also contributing something. (Lol, I'll fix it, j/k.)
Anyway, this can be closed if you ask me.

**Comment by jdolan** [comment]
SWEET! I passed the test!
