### ISSUE TITLE
Slimyplace: Missing textures

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#55]
There is a missing texture on slimyplace. (The side of the stair is missing a texture).

This is possibly/probably related to a failure to load slimyplace/lead1_1 slimyplace//metal15_2 slimyplace/metal15_3sml slimyplace/metal5_2

![quetoo030](https://cloud.githubusercontent.com/assets/567688/19838813/37c68002-9e94-11e6-9b25-84c1595a2f8b.png)
![quetoo031](https://cloud.githubusercontent.com/assets/567688/19838812/37c65f82-9e94-11e6-8337-80afe0fd0478.png)

**Comment by Panjoo** [comment]
Good find there WickedShell, sometimes I'm using the caulk texture too vigorously while I'm tidying things up even though it's not necessary to do so. ;)

I've already been fixing those old material references and retextured that brush. I'll upload/sync this map and a bunch of other tweaked map pk3's that I've been working on.

**Comment by Panjoo** [comment]
Commit [12e992d](https://github.com/jdolan/quetoo-data/commit/12e992d9cce32cf5e6b34a92faddb500fe5d5781) <- updated Slimyplace -fixed visible caulk texture on staircase.

:mag:
