### ISSUE TITLE
Blaster "wings" don't agree with new shell code

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#59]
So this issue is very specific. I added some new code that welds together obj models if "r_shell" is 2 (consider it high quality shell mode). It looks great, but the blaster has a very specific issue with it.

off: http://i.imgur.com/i5srYNK.jpg
on: http://i.imgur.com/8BlqpmB.jpg

(the shell size is increased just to show the issue a little better. the actual shell size for view weapon is much thinner)

The wings on the side of the model are a V sort of face - unfortunately, no matter how I normalize the vertices, that point at the end of the wing always wants to point inwards.

This can be fixed one of two ways:
* weld the vertices at the tip of the Vs - Panjoo may not want this if it makes the model look too phongy though
* change the wings to use a thin polygon instead of a flat connection (as in \_/ vs V).

Up to Panjoo, he knows the models quite a bit better than me :)

**Comment by Panjoo** [comment]
I'm the last one to diss other people's work but most of these weapon models were (some still are) kind of messy and have an unfinished feel to them, making it very hard to properly UV-map them without rescaling and fixing stuff. In a lot of places the parts seem to have been freely stuck together causing unneeded and unseen polys. Add in the fact that the models were clearly made by mirorring one half to get the symmetry, but they didn't combine/merge the (now doubled) faces you get in the middle from that method.

I've found the same sort of problem when redoing the BFG (the old model also had flat, even one-sided faces). The Hyperblaster was even worse and the Rocket had to be completely redesigned from scratch. It's almost like they never got around to finetuning these models. I'll see if I can add some polys to the bottom of those wings without having to make a lot of changes to the skin.

You're talking about these things in red here, right?

![blastertris](https://cloud.githubusercontent.com/assets/10857572/20260402/c22875b8-aa59-11e6-96ae-dc79045e5a83.png)

**Comment by Paril** [comment]
Panjoo spitting the hot fire - get shit on, blaster model creator! Interesting to note too that the model also looks like garbage in the old shell code - the same problem exists where the faces protrude in an odd manner.

Yeah, you can see the issue highlighted in the second screenshot at the bottom-left - they are shell-less because the normal is facing inwards rather than outwards. In the first screenshot, the faces create an odd intersection at that point.

Do you think you could run through all of the models and do a clean/optimize? You're right, there's a lot of extraneous faces there that really shouldn't be there.

**Comment by Panjoo** [comment]
Alright, the Blaster model got cleaned up and it sure was a blast.
I just pushed this commit to master [e1c380d](https://github.com/jdolan/quetoo-data/commit/e1c380d2510f12dee5d502c134049e5c676511d6)

Made a glow skin too. The model is now welded and 75 faces lighter and I also removed some of those center vertices from the top part. I could've easily removed twice as many but the parts on the back aren't in view and it was tricky enough to manipulate the existing UV-map coordinates after removing stuff, so f*ck it:P

Apparently there were some duplicate faces causing (z-fighting?) black spots in the normalmap that wouldn't go away so these needed to be hunted down. Of course the actual skin and normalmap had to also be edited and so you go from one thing to the other. Lol, all this work and you can hardly tell a difference, but at least the newer shell code should look right now. Hopefully:)

**Comment by Paril** [comment]
http://i.imgur.com/rxfCbG6.jpg

Looks good now. It doesn't look as good without shell though: http://i.imgur.com/H68qCSB.jpg

**Comment by Panjoo** [comment]
Standing next to a light makes it look worse.  But this is what I've been trying to say, welding all vertices causes that phong-ish smoothing effect so you're losing some hard edges and definition. At least that's what I think you mean...
This is turning out too much work for a quad glow effect on a weapon that most players won't be using when they have that powerup. But I can always weld/unweld some vertices again if needed, no problem.

**Comment by Paril** [comment]
You don't have to weld. I already added a new code path that welds the vertices for the shell effect while leaving the actual rendered model unwelded. Sorry if I wasn't clear about that.

I only wanted the wings fixed :)

**Comment by Panjoo** [comment]
Hehe yes I know, but I couldn't just fix the wings without welding and reconnecting old and new vertices 
(cleaning up the unnecessary vertices created holes in the model.)
What I'll do is unweld some of the outer edges to get back some of the sharper corners.

**Comment by Panjoo** [comment]
Okay, done and uploaded. The bloody thing looks better now;) Let me know what you think.

BTW, do you happen to know why the Quad model is not showing its normalmap? I could be wrong but it look like it's been disabled.
