### ISSUE TITLE
Hook sounds

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#61]
Need some sounds for our brand new grapplin' hooks.

I've always been really partial to the CTF Grapple sounds from Quake 2 (https://youtu.be/mGvQcCfawJg?t=233) but anything you can think of would be great.

We need:
hook_fire - a distinct sound of a firing hook. Hookmod for Quake 2 used the Medic revive-latch sound for this, but as always, defer to sound expert.
hook_latch - the hook grabbing onto something. Any kind of metal cling sound will do here honestly.
hook_pull - some kind of sound to represent being pulled (or, in the case of swing hook, grow/shrink) towards the hook. A mechanical whirr will probably do, as long as it's not annoying (the CTF Grapple from Q2 was extremely annoying, haha)

**Comment by jdolan** [comment]
I'd be happy with sounds that were somewhere between Q2's and something more realistic. Firing a grappling hook could sound like a muffled / suppressed gunshot, and a rope flying sound would be pretty cool while the grapple is on its way out (hook_fly).

@anthonywebb1 The grapple hook is available in the game now, so you can get a feel for it. Load up any map, and set `g_hook 1` at the console. It's bound to the middle mouse button by default, but the alias is `+hook` if you care to bind another key.

@Paril could you update the game code to actually source these sounds at the appropriate times? That way Anthony can hear them in action as he works through them.

 * [ ] `sounds/objects/hook/fire.wav` - Client fires hook
 * [ ] `sounds/objects/hook/fly.wav` - Hook on the way out (loop)
 * [ ] `sounds/objects/hook/pull.wav` - Hook pulls or lengthens (loop)
 * [ ] `sounds/objects/hook/hit.wav` - Hook hits the world

I think we should repurpose one of the giblet "hit" sounds for when the hook hits flesh.

**Comment by Paril** [comment]
Will do.

**Comment by Paril** [comment]
Updated your comment to include detach wav.

**Comment by kaadmy** [comment]
This seems like a fairly simple one, is anybody available to get this done?
Having the blaster as the current sound is a bit confusing right now.

**Comment by anthonywebb1** [comment]
@kaadmy Hey, sorry it's taken so long, been a bit hectic changing jobs and moving house this year, I'll try to take a look at it over the weekend.

**Comment by kaadmy** [comment]
Great :) Haven't seen you around for a while, so I figure you were busy with real life :D

**Comment by anthonywebb1** [comment]
Haha, yes it's been busy first with Christmas and then lots of life stuff this year, the sound stuff as gone to the back of my mind a bit, but it's about time to get back to it :)

**Comment by anthonywebb1** [comment]
Making progress on the g_hook, have the fire, pull and hit sounds done already... just to keep you in the loop it should hopefully be ready by next weekend.

**Comment by Paril** [comment]
Nice! Can't wait to hear them!
