### ISSUE TITLE
Updated jump sounds that include player grunt

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#62]
@anthonywebb1 provided 5 updated jump sounds that incorporate a male grunt. Zip attached. 

[jumps.zip](https://github.com/jdolan/quetoo-data/files/643261/jumps.zip)

If we decide to merge these in, we'll want to save a couple of the old ones and use them for ladder movement sounds. Currently, as players climb ladders, we emit the jump event / sound.

**Comment by Panjoo** [comment]
Definitely use these jump sounds, they fit right in. It's so much better to have this extra sound cue as to the whereabouts of jumping opponents. With the old sounds you hear almost nothing. Nice work @anthony

**Comment by kaadmy** [comment]
I believe this is finished now? Closing.

**Comment by anthonywebb1** [comment]
Yes I have done those sounds :)


________________________________
