### ISSUE TITLE
Pretty message strings for all maps

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#64]
Some of our maps don't use colorized message strings. This is nitpicky, I know, but it'd be great if they did. Updating them would require editing the .map file (even in a text editor) and then just running `quemap -bsp -onlyents maps/foo.map`. It'd take a few minutes per map, with unpacking and repacking.

**Comment by kaadmy** [comment]
Oops, closed by accident, work on this anyway.

**Comment by kaadmy** [comment]
What colors should the names be?
Is `^1T^7he ^1E^7dge ^4by ^3P^7anjoo` okay?

**Comment by kaadmy** [comment]
See #81.

**Comment by kaadmy** [comment]
This is a very simple thing to finish, I can do it with half hour of time pretty easily.
Any specifics on colors? I think green+white for all the Q1/Q2 remakes is good, and all other maps use their "color"+white.

**Comment by jdolan** [comment]
Yea, straight up green messages for the Quake and Quake2 remakes, and then "map color" plus white for all other maps. Thanks @kaadmy!

**Comment by kaadmy** [comment]
Isn't this closed now? I'm not sure if the map titles are actually fixed now but the relevant branches are merged/deleted by now.

**Comment by jdolan** [comment]
They're mostly fine. I think Aerowalk has red and yellow text, yet should probably be blue / indigo / white.

**Comment by kaadmy** [comment]
@Panjoo thoughts on map title colors? If you don't have a preference I'll change Aerowalk's title per @jdolan's and close this issue.
