### ISSUE TITLE
Rocket skin / model is messed up

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#67]
For some reason, the rocket model is drawn with a huge black blotch on it. I always thought it was lighting related, but it's not. There's something wrong with the model. It's an MD3 that we should convert to OBJ, anyway.

**Comment by Panjoo** [comment]
I couldn't find any visible vertex errors in the model but its texture seemed to have an alpha-channel mask so I removed that. I never really noticed any black blotch on the model so hopefully this fixes it.

I went ahead and converted to OBJ and also increased the model size according to its world.cfg.
After converting, the model didn't spin around the right axis anymore so I had to rotate it 90 degrees. The skin was kinda crappy so I painted some details over it, now it's still crappy but less.

**Comment by jdolan** [comment]
Yep, fixed!
