### ISSUE TITLE
Warehouse bottom floor is slippery for non-players

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#68]
https://gfycat.com/LikelyFluffyHatchetfish

**Comment by jdolan** [comment]
If this is code related, I wonder if that floor sits at `0.0` Z...

**Comment by Paril** [comment]
This might be code-related. Your "TODO: use ent->locals.clip_mask?" seems to be correct, if I use that instead of MASK_SOLID they don't slide any more.

**Comment by jdolan** [comment]
:shipit:
