### ISSUE TITLE
We need Q2Guard to accompany the QForcer!

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#72]
http://www.tabun.nl/3d_work_view.php?view=m_q2guard

**Comment by jdolan** [comment]
Email sent to Tabun, awaiting his blessing.

**Comment by jdolan** [comment]
> Hi,
> 
> I can't even remember why I wouldn't have allowed it before --
> if it was asked before.
> 
> But sure, go for it.
> All I ask is to give credit where due and to avoid out-of-style edits.
> 
> Enjoy,
>    Tab

We're good to go!
