### ISSUE TITLE
Weapon view alignment still not quite right

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#77]
The weapon `view.cfg`s could still using some work. I hate to harp on this, but they're just not consistent.

**Comment by kaadmy** [comment]
Which ones stand out the most here?

**Comment by jdolan** [comment]
`give all` and then cycle through them. They're all over the place.

Btw @Panjoo @Arseflute, I added a few new cvars that should really help with object scale and origin:

    cg_entity_bob 0
    cg_entity_pulse 0
    cg_entity_rotate 0

Will yield completely stationary pickup items.

    cg_bob 0

Will disable your own view bobbing, so you can really see these things and examine them up-close.

Hope this helps with nailing down our item origins and scales!

**Comment by Arseflute** [comment]
thats going to be awesome to be honest ;)

**Comment by jdolan** [comment]
There's a new map available, called `sandbox`. It includes all items / weapons / flags. You can use it with the above cvars to see exactly how our weapons stack up.

**Comment by kaadmy** [comment]
Eh, I'll try to take this one on quickly to try to line the first-person models up a bit.

**Comment by kaadmy** [comment]
Made a few more changes to kaadmy/model_tweaks, take 'em out for a test run and tell me how they are now.

**Comment by jdolan** [comment]
Nice. Pretty good. I'm going to continue to nitpick :P Some of these will require editing the models..

 - [ ] Blaster large in both 1st and 3rd person view. It should be smaller than the other guns.
 - [ ] Shotgun sits a little high 1st person. Also slightly large. Should be smaller than RL.
 - [ ] Super shotgun is too fat / chunky 1st person (it's bigger than RL)
 - [ ] GL a smidgen low 1st person
 - [ ] RG and BFG maybe too large 1st person?

More feedback in this screenshot of `sandbox`.

![items](https://cloud.githubusercontent.com/assets/643118/23796312/47b248f8-0568-11e7-9785-30e61cab7a48.jpg)

**Comment by kaadmy** [comment]
I purposely made the BFG huge in first-person, otherwise there isn't much similar on it to _Big Fucking Gun_.
GL is also low in first-person, otherwise it filled a lot of the view since it's really wide, it looked to powerful compared to the other weapons.
I made HB a little smaller since it looked larger than RL in third person, didn't quite fit well.
SSG should be larger first-person than the SG, IMHO this is already good but maybe _slightly_ large.

**Comment by jdolan** [comment]
I pushed some changes to your branch, which included re-adding world.cfg's to "fix" a bunch of the weapons. Here are some screenshots I took with `cg_entity_bob 0`, `cg_entity_rotate 0`:

Before:
![broken-ish](https://cloud.githubusercontent.com/assets/643118/23819311/87877cd6-05d2-11e7-9e7f-e88bf16cca08.jpg)
![broken-ish-top](https://cloud.githubusercontent.com/assets/643118/23819313/8b87cdea-05d2-11e7-8a8b-03e823be569d.jpg)

After:
![fixed-ish](https://cloud.githubusercontent.com/assets/643118/23819319/938c6d98-05d2-11e7-969e-d5c58ebccb88.jpg)

If you *want* to re-export the models, applying their respective `world.cfg`s, that'd be great. Then the view.cfg and link.cfg's should all be mostly uniform.

**Comment by jdolan** [comment]
@kaadmy Did you want to re-export the weapons, or just go with my modified world.cfg's?

**Comment by kaadmy** [comment]
I can reexport them so they're uniform, it shouldn't be much trouble.

**Comment by jdolan** [comment]
👍

**Comment by kaadmy** [comment]
With @Panjoo's current tweaks in master, is this finished now or does it need more polishing still?

**Comment by jdolan** [comment]
Sure.
