### ISSUE TITLE
Lilith: Geometry is poorly clipped near RL

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#83]
Ceiling features on Lilith near the RL don't block movement. (I am to tired to remember the mapping name for this) All the attached ones can be run through by the player.
![quetoo064](https://cloud.githubusercontent.com/assets/567688/22814749/398f94f8-ef13-11e6-93bc-ea87b2d41348.png)
![quetoo065](https://cloud.githubusercontent.com/assets/567688/22814748/398f342c-ef13-11e6-83eb-1a58b52cfc88.png)
![quetoo066](https://cloud.githubusercontent.com/assets/567688/22814750/3994374c-ef13-11e6-8849-1ef9e17dd548.png)

**Comment by Panjoo** [comment]
Noted, some things appear to have been set as `mist`.

**Comment by jdolan** [comment]
@Panjoo what do you think of retexturing this map in baseq2 garb? It's something we were chatting about in Discord the other day. And I'm not suggesting that you do it, but.. I think the map would look a lot better. You?

**Comment by Panjoo** [comment]
Baseq2 style could maybe look better but take it from me that retextureing rarely works. Not without killing the map's spirit.
It's one of the reasons I try to make my q2 ports stay close to the real deal. I know first hand that mappers almost always get inspired by a texture set, and they build the map with that in mind. Take the walls in Lilith for example, the idea to create holes in the walls and have debris nearby came from that texture. 
If you go and try to repaint it then sooner or later you're going to have to rebuild a large portion of brushwork to make the new textures fit and align and combine. Probably need new lighting and skybox as well. 
If you ask me the map would benefit most from better normalmaps and perhaps from using less textures to make it not so busy. And some tighter and less bulky trimwork. Months ago I already made a start with the normals but it had to go on the shelf. I could give it another try though.

**Comment by jdolan** [comment]
"..not without killing the map's ... *spirit*" I see what you did there.
