### ISSUE TITLE
Lilith: Escape through the ceiling

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo-data#84]
You can escape through what is meant to be a view through towards skybox/upper geometry with the hyperblaster via wallclimibing. It also explains why there are textures up here in the "unreachable" area. There is a decent number of faces that a user shouldn't be able to see.

Unless someone thinks this is good behaviour, but most people won't know about it.

![quetoo067](https://cloud.githubusercontent.com/assets/567688/22814809/c8a5606e-ef13-11e6-8f75-b51f0e5e4303.png)
![quetoo068](https://cloud.githubusercontent.com/assets/567688/22814810/c8b24ba8-ef13-11e6-93bb-71315fb34b27.png)

**Comment by Panjoo** [comment]
Oh look, monkey boy has found a hole and climbed out again;)

I think I'll just place clips over the roof areas and caulk off the normally unseen faces there. The closer I look at this map in Radiant the more it feels rushed and unfinished in a lot of those places.
And the normalmaps for this texture set are also not what they could be... hmmm:/

**Comment by Panjoo** [comment]
^
This has been fixed and then some:)

https://github.com/jdolan/quetoo-data/commit/d656c3f27b30ba0de04750fcab17e863ebe8a3a5

**Comment by jdolan** [comment]
Looks great!
