### ISSUE TITLE
Allow materials to specify underwater screen blending

### ISSUE THREAD

**Issue by Quake2Beaver** [jdolan/quetoo-data#86]
would like the ability to make water clear on all maps while underwater 
it looks good with cg_draw 0  but i was informed that would take away vital elements of the game
 id like for players to be able to see clearly in water with out typing a command or losing those vital elements.

![quetoo080](https://cloud.githubusercontent.com/assets/23428363/22951549/40765238-f2cf-11e6-85fc-d806018444f8.png)
![quetoo079](https://cloud.githubusercontent.com/assets/23428363/22951550/4077a282-f2cf-11e6-8349-411ac9fc1cc3.png)
![quetoo078](https://cloud.githubusercontent.com/assets/23428363/22951551/40788760-f2cf-11e6-9b95-eee16ffb3472.png)

**Comment by kaadmy** [comment]
Maybe `cg_draw_blend_water` as a CVar, or should this be a map option?
Map worldspawns could also have a `waterblend` boolean.

**Comment by Paril** [comment]
It *might* be possible to tie this into material system... @jdolan would this work if we had like "water_blend <rgba>" and we use that for blend colors? Then lava/slime/water colors can be not hardcoded into the game too.. only thing is I dunno how we get materials of the water surface from the brush.

**Comment by jdolan** [comment]
R_LeafForPoint will return the BSP leaf you're in. Iterate the surfaces until you find the material with `water_blend` (or whatever) defined on it's texinfo.

**Comment by Paril** [comment]
Cool, I'll see about doing that if it's not too intensive to do per frame.

**Comment by jdolan** [comment]
We could actually iterate the leafs at map load and resolve any `blend_color`, storing it on the `r_bsp_leaf_t`. Then each frame only requires a single call to `R_LeafForPoint(r_view.origin)` -- which we're already doing in `R_MarkLeafs`

**Comment by jdolan** [comment]
I'd even go as far to suggest that we resolve the texture's average color and use that as the default blend color. That way, for 90% of the water / lava / slime textures in the game, blend is automatically applied with a reasonable color. I *think* we are already resolving the average color of each texture, too.

**Comment by Paril** [comment]
That sounds great actually - and yes the average colors are stored in r_image_t

**Comment by kaadmy** [comment]
There's a cvar now for this: `cg_draw_blend_liquid`, should this be closed?

**Comment by jdolan** [comment]
If you want to lift the above discussion into a new issue, sure this one can be closed. Otherwise, I'd prefer to leave it open, as there's an interesting feature described above that I don't want to lose track of.

**Comment by kaadmy** [comment]
Sure, I'll just rename this issue instead.

**Comment by jdolan** [comment]
This can and should just be simplified as follows:

Cg_DrawBlendEffect should have 3 hard coded colors depending on cgi.PointContents:
 * Lava, red / orange
 * Slime, green
 * Water, blue

These colors can be very subtle, because many water volumes will now include colored fog to address this. Any takers? @ypsvlq this is a layup of a ticket for cgame.

**Comment by jdolan** [comment]
This is actually already implemented in Cg_DrawBlend. My bad! Closing out :)
