### ISSUE TITLE
Gib_3 (head) is always floating above the ground

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo-data#87]
While fixing the gib skins and testing out the newer models I noticed that the head doesn't want to rest on the ground like the other gibs.
They all sit nicely on the Origin but the head is stubborn. I suspect something has been done to the head gib to give it special treatment. The soon as I switched gib_3 with gib_1 the head was resting closer to the ground like it should.

**Comment by jdolan** [comment]
It could be the bounding box that I set for it in the code:
https://github.com/jdolan/quetoo/blob/master/src/game/default/g_client.c#L303

You can see the 3rd set of mins/maxs expect the model to be about 18 units across, 9 units in all 3 directions. So this could be view.cfg, or the model itself, not agreeing with that sizing.

**Comment by jdolan** [comment]
Btw, the mins/maxs are set there so that the gib collides correctly, approximately with the right sized box.

**Comment by Panjoo** [comment]
The gib only has a (dummy) world.cfg, no view.cfg. And modelers don't really use units, so what now? 

I've got the head gib more or less at a good scale now and I don't want to have to upscale it and make it too big. As a test I scaled it up by 1.5 and at that size it seems to touch the ground. Would that mean that if you changed the 3rd set of mins/max to expect 10 units across, 5 in all directions, it will look better?  
I guess I'll just upload this stuff very soon so you can finetune it.

**Comment by jdolan** [comment]
I meant `world.cfg`, not `view.cfg` -- my bad.

Yes, don't worry about how they clip right now. If you push updated models with centered origins at the sizes you want them, I can make them clip correctly :)

**Comment by jdolan** [comment]
Will be closed via #75
