### ISSUE TITLE
Cut up and mix down new sounds for Guard player model

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo-data#88]
Brian Watts has created some new sounds for the Guard player model. See attached. They are a single .wav file right now, so they need to be cut up, possibly leveled, and then merged into `player-guard.pk3`.

[guard-sounds.wav.zip](https://github.com/jdolan/quetoo-data/files/778880/guard-sounds.wav.zip)

**Comment by Paril** [comment]
These have been chopped and placed in src. Not ready for prime time yet though.

**Comment by ptrvrhvn** [comment]
I've done a first pass at them, haven't tested exhaustively but they sound decent enough to me.
I just overwrote the default ones to test, since otherwise it didn't seem to work? Haven't looked into it any further :)

**Comment by jdolan** [comment]
Sick! Nice one @ptrvrhvn. We should try to bundle these up into `player-guard.pk3` (and then figure out why the game is too dumb to play them from there). I think we might also need a README or something to credit Brian Watts (ShadowsFate) for these sounds. I'll take that on. @Paril since you were so hot to get these, do you think you'd have time to get them working from the correct location?

**Comment by jdolan** [comment]
It looks like maybe when extracting client loading into the cgame, we forgot to either bring over, or expose, model-specific sound sample loading.

`S_LoadModelSamples` exists but is never called. Cgame exposes `cgi.LoadSample` but not `cgi.LoadModelSample`. Looks like we just need to move a few things around and call the right function for these sounds to work.

The `player-guard.pk3` has been updated to include the mixed down sounds. So this just needs code at this point.

**Comment by kaadmy** [comment]
Should this issue be closed and open a new issue relevant to custom model sounds?

**Comment by jdolan** [comment]
Up to @Paril. However he wants to track it.

**Comment by jdolan** [comment]
This is done and working :)
