### ISSUE TITLE
hook non-responsive / grappling hook effects.

### ISSUE THREAD

**Issue by Quake2Beaver** [jdolan/quetoo-data#89]
hook could be more responsive with auto refire hook when hooking non-hookable object like a player, the sky, etc

 as long as the hook key is being held down a hook should be firing or attaching to an object until released.

(i was pressing the hook key at a rapid pace tonight and sometimes i would hit the key expecting a hook to fire but nothing comes out and my finger is holding down the key.  if i try to hit the hook key twice at a rapid pace the second time i press down it does not register.. i tested about 10 time in a row each time the 2nd key press doesn't register.)

when grappling hook hits a surface/object spark or blood particles should be seen.

the sparks help a player know when their hook connects and helps them time their moves.

**Comment by jdolan** [comment]
Closing this out, it belongs in `quetoo` not `quetoo-data`. See https://github.com/jdolan/quetoo/issues/425
