### ISSUE TITLE
Chest gib

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#90]
We still need one larger gib to be used as a chest piece. I love the current new gibs, although head needs to be scaled, but the one thing missing is a central piece. After that I think we can finally call gibs done for now :)

@Panjoo and @Arseflute, pinging since they relate to you.

**Comment by Arseflute** [comment]
Crap I completely forgot about that one

**Comment by Panjoo** [comment]
> although head needs to be scaled

@Paril see #87

@Arseflute - I'd suggest using the chest model you already made, but with less meat on the backbone.
And please downscale the skin to 512x512 as I did with the other gibs.

**Comment by Paril** [comment]
Sounds good!

@Arseflute make the chest folder name "gib_4", that'll work fine :)

**Comment by Arseflute** [comment]
will do.

**Comment by Arseflute** [comment]
@Panjoo can you explain a little further exactly what you mean by less meat on the backbone?

**Comment by kaadmy** [comment]
Maybe move the back farther "into" the rest of the body, ie. sunken in.

**Comment by Arseflute** [comment]
that sounds like more meat around the back bone. Then again i am a little backwards

**Comment by Panjoo** [comment]
I'd like to give some more emphasis to the backbone and ribscage so if you could hollow it out some more I think it'll look better. We can always draw in some more ribs on the outside but it looks too much like a solid chunk now.

**Comment by Arseflute** [comment]
![](https://cdn.discordapp.com/attachments/276485695030427648/282354272861945856/unknown.png)

![](https://cdn.discordapp.com/attachments/276485695030427648/282353639723368449/unknown.png)

![](https://cdn.discordapp.com/attachments/276485695030427648/282353727036456962/unknown.png)

![](https://cdn.discordapp.com/attachments/276485695030427648/282353677501464580/unknown.png)

Hopefully this will work?

**Comment by Arseflute** [comment]
it still wont let me post a .zip file for some reason, i will have to send you the file over discord @Paril

**Comment by Panjoo** [comment]
First pic looks okay in perspective but overall it feels like an Armor jacket. It's going the right way though.

![chest](https://cloud.githubusercontent.com/assets/10857572/23092865/76d5ac04-f5d4-11e6-9d44-3c1386caccf7.jpg)

**Comment by Arseflute** [comment]
Yeah it needs some tweaking after I looked at it in game for sure

**Comment by Arseflute** [comment]
![image](https://cloud.githubusercontent.com/assets/25470615/23096580/8032cb6a-f5ed-11e6-9586-99412833d2af.png)

Edited, and rescaled a little.

**Comment by Panjoo** [comment]
Yep, I think that's better already. 
I probably would have taken away the bottom half though and kept only the spine hanging out. But I know how much work it can be to edit this stuff is so it's up to you.

Here's a fabricated image of what I mean;
![shorter](https://cloud.githubusercontent.com/assets/10857572/23097387/83e8c15c-f632-11e6-98ea-cb60d65b1f63.jpg)

I'm preoccupied at the moment but if you don't mind I could always modify a little of this and a little of that on this gib when I have time. You did most of the work anyway.

**Comment by Arseflute** [comment]
I can do something to that effect.. im sure your hands are quite full, and i enjoy the process, the more ya do the more ya learn right? well i hope so anyway lol..  Only other thing i have going on is a map, so i will give it a shot and see what happens. thanks for the image tho, that will help out tremendously

**Comment by Arseflute** [comment]
![image](https://cloud.githubusercontent.com/assets/25470615/23099516/0c52d2f4-f637-11e6-969a-684f448a68ac.png)
this is a little closer, trying to do it without causing errors and re uvmapping the whole thing.. but im thinking i may do that anyway

**Comment by Arseflute** [comment]
![image](https://cloud.githubusercontent.com/assets/25470615/23099522/4fe389b4-f637-11e6-9cc9-38bf7b0faca8.png)

**Comment by Panjoo** [comment]
Definitely better this way.:)
As for uvmapping and such, here's a trick I use to help with preventing ugly strech effects. I've made this "checkers" pattern texture that I temporarily slap onto a model if I notice bad areas.

The squares don't have to be aligned but roughly be the same size everywhere. So try to prevent one area having just a few big squares while others have many tiny ones. This is so the actual skin will be evenly scaled all around the model. 

So if there's an area with the squares too big, its part in the uvmap should be expanded.
If there's an area with the squares too small, its part in the uvmap should be contracted.

![checkers](https://cloud.githubusercontent.com/assets/10857572/23103093/9438c7fe-f6b5-11e6-967a-8834cf7ec632.png)

**Comment by kaadmy** [comment]
Blender has a builtin image generator to generate UV test images :D
http://blenderpdx.org/wp-content/uploads/2015/02/1.5-UV-Test-Grid.png

**Comment by Arseflute** [comment]
yeah, the uv was good on that, but i moved the verts to avoid re uv at the moment.. im gonna go back in on the new shape now and remove a lot of tris and re uv the whole thing and texture it.. just was trying to hurry and get a complete gib set

**Comment by jdolan** [comment]
This is able to be closed, yes?

**Comment by kaadmy** [comment]
Seconding jdolan.
