### ISSUE TITLE
Special stain textures

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#94]
Now that stains support textures, I'd like to see some special textures for stains that we can use. I'm gonna make some dummy textures that you can use to test them in-game and hook them up to the individual effects. "stain_burn.tga" is the test texture for explosions and is hooked up to them currently.

The stains may need size adjustments as well - if you need to test stains with a larger size, use r_stainmap 1.5 or 2.0 (or any other number) to multiply the stain sizes.

**Comment by Panjoo** [comment]
https://github.com/jdolan/quetoo-data/commit/77193ca54638ae16fa1ebb2d109ee730d51d2f91
