### ISSUE TITLE
Tech sounds

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo-data#95]
We need some sounds for the new CTF techs.
We already have dummy sounds hooked up and working in-game; see "default\sounds\tech".

* [x] haste.wav is played when firing a shot with Haste
* [x] pickup.wav is played when picked up a tech
* [x] regen.wav is played every ~1 sec when regenerating health
* [x] strength.wav is played when firing a shot with Strength
* [x] vampire.wav is played when health is successfully succ'd from an enemy

Thanks!

**Comment by kaadmy** [comment]
I think the pickup sounds are done for techs now, correct?

**Comment by anthonywebb1** [comment]
Yes, that should be all of them done now.

Sent from my iPhone

On 7 May 2017, at 23:16, KaadmY <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the pickup sounds are done for techs now, correct?

**Comment by kaadmy** [comment]
Um, this should be closed..?

**Comment by jdolan** [comment]
Yes, I hear these in game now. SWEEEEET.
